name: Update MVV data

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

concurrency:
  group: update-mvv-data
  cancel-in-progress: true

permissions:
  contents: write


jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --locked

      - name: Update MVV data
        run: uv run python scripts/update_parquet.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/realtime/mvv_realtime.parquet
          git add docs/munich_delay_statistics.png
          git add docs/munich_delays.png
          git add -f docs/delay_comparison.png

          git diff --cached --quiet || git commit -m "Update MVV data and plot"

          git push